on: [push]

jobs:
  test-migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test Migrations
        run: docker compose build && docker compose up --abort-on-container-exit
