on: [push]

jobs:
  test-migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: install poetry
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: run upgrade migrations
        run: |
          poetry run alembic upgrade head

      - name: run tests
        run: |
          poetry run pytest

      - name: run downgrade migrations
        run: |
          poetry run alembic downgrade base
